apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guest-namespace
  name: guest-deployment
  labels:
    part-of: guest-part
    component: guest-backend-server
    name: guest
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: guest-part
      component: guest-backend-server
      name: guest
      instance: guest-instance
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: guest-part
        component: guest-backend-server
        name: guest
        instance: guest-instance
        version: 1.0.0
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: guest-container
          image: academyitwill/guest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          