apiVersion: v1
kind: Service
metadata:
  namespace: guest-namespace
  name: guest-service
  labels:
    part-of: guest-part
    component: guest-backend-server
    name: guest-service
    instance: guest-service-instance
    version: 1.0.0
    managed-by: kubectl
spec:
  selector:
    part-of: guest-part
    component: guest-backend-server
    name: guest-service
    instance:  guest-service-instance
  ports:
    - port: 80
      targetPort: http
      nodePort: 32212
  type: NodePort
